---
title: 2017-01-10 <br>Examen de Cálculo
lang: es
date: 2017-01-10
---

Grados: Farmacia y Biotecnología

:::{#exr-1}
Un cultivo de bacterias crece al ritmo de la raíz cuadrada del número de bacterias en el cultivo.
¿Cuánto se habrá incrementado el número de bacterias con respecto al número inicial tras una hora del comienzo del cultivo?
¿Cuánto tiempo debe pasar para que el número de bacterias inicial se haya cuadruplicado?
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $x(t)$ el número de bacterias en el instante $t$.  
Solución particular: $x(t)=\left(\frac{t}{2}+C\right)^2$.  
El número de bacterias habrá aumentado $\frac{1}{4}+C$ una hora después del comienzo del cultivo.  
El número de bacterias se habrá cuadruplicado en el instante $t=2C$.
:::

:::{#exr-2}
En un proceso químico, la temperatura depende de la cantidad de dos sustancias $x$ e $y$ de acuerdo a la fórmula $T(x,y)=4x^3+y^3-3xy$.
Teniendo en cuenta que las cantidades de $x$ e $y$ no pueden ser negativas, estudiar los extremos relativos y los puntos de silla de la temperatura.
:::

:::{.callout-tip collapse="true"}
## Solución
$T$ tiene un punto de silla en $(0,0)$ y un mínimo local en $\left(\frac{\sqrt[3]{4}}{4},\frac{\sqrt[3]{2}}{2}\right)$.
:::

:::{#exr-3}
Un modelo ecológico explica el número de individuos de una población mediante la función

$$
f(x,t)=\dfrac{e^t}{x},
$$

donde $t$ es el tiempo y $x$ el número de predadores en la región.
Calcular el valor aproximado de individuos en la población para $t=0.1$ y $x=0.9$ utilizando el polinomio de Taylor de segundo grado de la función en el punto $(1,0)$.
:::

:::{.callout-tip collapse="true"}
## Solución
Polinomio de Taylor de segundo orden de $f$ en el punto $(1,0)$: $P^2_{f,(1,0)}(x,t)=3-3x+2t+x^2+\frac{t^2}{2}-xt$.  
$P^2_{f,(1,0)}(0.9,0.1)=1.225$.
:::

:::{#exr-4}
Una partícula se mueve en el espacio de manera que su posición en cada instante $t$ viene dado por la función $f(t)=(e^{t/2}, \operatorname{sen}^2(t), \sqrt[3]{1-t})$.
Se pide:

1. Calcular los vectores velocidad y aceleración en el instante $t=0$.  
   Nota: La velocidad es la variación del espacio con respecto al tiempo y la aceleración es la variación de la velocidad con respecto al tiempo.
2. Calcular el plano normal a la trayectoria de la partícula en el instante $t=0$.
:::

:::{.callout-tip collapse="true"}
## Solución

1. $f'(t)=\left(\frac{e^{t/2}}{2},2\operatorname{sen} t \cos t, \frac{-(1-t)^{-2/3}}{3}\right)$ y $f'(0)=\left(\frac{1}{2},0,-\frac{1}{3}\right)$.  
$f''(t)=\left(\frac{e^{t/2}}{4},2(\cos^2 t-\operatorname{sen}^2 t), \frac{-2(1-t)^{-5/3}}{9}\right)$ y $f''(0)=\left(\frac{1}{4},2,-\frac{2}{9}\right)$.
2. Plano normal a la trayectoria en el instante $t=0$: $3x-2z=1$.
:::
